### 10.2.1 Implementation of NN

In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
model = Sequential()

# pass no. of nodes that we want on this layer, activattion function
# all the inputs received by each 10 nodes will be multiplied with their weights and summed up. Then passed as input to sigmoid function.
# sigmoid function will give result b/w 0 and 1
# type of input is defined in 1st hidden layer of model
# output of input_style (input) is sent to hidden layer as input
# output of hidden layer goes to output layer as input
# output of output layer is final output of model
layer1 = Dense(10, activation='sigmoid', input_shape=(3,))   # hidden layer
layer2 = Dense(1, activation='sigmoid')    # output layer

# add layers to model
model.add(layer1)
model.add(layer2) 

In [3]:
# Param are thetas
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                40        
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 51
Trainable params: 51
Non-trainable params: 0
_________________________________________________________________


### 10.2.2 Input Shape and Model Training



In [4]:
import numpy as np

In [5]:
# dummy dataset
# 3 features per doc
input = np.array([ [3,3,1], [4,3,1], [3,1,2], [2,3,1] ])

# labels for each instance of input respectively
output = np.array([0,0,1,1])


In [6]:
print(input.shape)
print(output.shape)

(4, 3)
(4,)


In [7]:
model = Sequential()

# we left the space after comma in input_shape indicates each of these 3 features in a doc is a scalar value
# input_shape(3,) indicates that each instance has 3 elements like [3,3,1]
# if we have 3 lists as elements in each instance like [ [ [2,1], [2,2], [2,3] ] ] then input_shape=(3,2,)
layer1 = Dense(10, activation='sigmoid', input_shape=(3,))   # hidden layer
layer2 = Dense(1,  activation='sigmoid')    # output layer

model.add(layer1)
model.add(layer2) 

In [8]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 10)                40        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 11        
Total params: 51
Trainable params: 51
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])

In [10]:
# epochs : no. of times model will run through all the instances
model.fit(input[:-2], output[:-2], epochs=3, batch_size=2, validation_data=(input[-2:], output[-2:]))

Epoch 1/3
1/1 [==============================] - 1s 689ms/step - loss: 0.4607 - accuracy: 1.0000 - val_loss: 1.0076 - val_accuracy: 0.0000e+00
Epoch 2/3
1/1 [==============================] - 0s 19ms/step - loss: 0.4530 - accuracy: 1.0000 - val_loss: 1.0204 - val_accuracy: 0.0000e+00
Epoch 3/3
1/1 [==============================] - 0s 20ms/step - loss: 0.4454 - accuracy: 1.0000 - val_loss: 1.0331 - val_accuracy: 0.0000e+00


### 10.2.3 Results and Evaluation

In [11]:
# dummy dataset
input = np.random.rand(10000,3)

# labels for each instance of input respectively
output = np.random.randint(2, size=10000)


In [12]:
print(input.shape)
print(input)
print(output.shape)
print(output)

(10000, 3)
[[0.95882298 0.06212022 0.03331903]
 [0.40967365 0.38593234 0.45903353]
 [0.51792265 0.90670337 0.26367775]
 ...
 [0.64835801 0.44983931 0.80559031]
 [0.94279767 0.39945231 0.91236352]
 [0.35095047 0.70623763 0.98656509]]
(10000,)
[1 0 1 ... 0 1 1]


In [13]:
model.fit(input[:-2000], output[:-2000], epochs=3, batch_size=64, validation_data=(input[-2000:], output[-2000:]))

Epoch 1/3
125/125 [==============================] - 0s 2ms/step - loss: 0.7153 - accuracy: 0.4964 - val_loss: 0.6983 - val_accuracy: 0.4995
Epoch 2/3
125/125 [==============================] - 0s 2ms/step - loss: 0.6955 - accuracy: 0.4967 - val_loss: 0.6938 - val_accuracy: 0.4855
Epoch 3/3
125/125 [==============================] - 0s 2ms/step - loss: 0.6937 - accuracy: 0.4911 - val_loss: 0.6936 - val_accuracy: 0.4915


In [14]:
model.evaluate(input[-2000:], output[-2000:])

63/63 [==============================] - 0s 1ms/step - loss: 0.6936 - accuracy: 0.4915


[0.6935609579086304, 0.49149999022483826]

In [15]:
model.predict(input[-10:-5])

array([[0.5072124 ],
       [0.506822  ],
       [0.5114924 ],
       [0.48954397],
       [0.49920666]], dtype=float32)

In [16]:
# 0 for < 0.5, 1 for > 0.5
model.predict_classes(input[-10:-5])

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[1],
       [1],
       [1],
       [0],
       [0]], dtype=int32)

In [17]:
pred_labels = model.predict_classes(input[-5:])
labels = output[-5:]

print(pred_labels)
print(labels)

[[1]
 [0]
 [1]
 [1]
 [1]]
[1 1 0 1 1]


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [18]:
from sklearn.metrics import precision_score, recall_score, f1_score

In [19]:
precision_score(pred_labels, labels, average='micro')

0.6

In [20]:
recall_score(pred_labels, labels, average='micro')

0.6

In [21]:
f1_score(pred_labels, labels, average='micro')

0.6

### 10.2.4 Using NN with IMDB reviews

In [26]:
import pandas as pd
corpus = pd.read_csv('sample_data/IMDB-Dataset.csv')

In [27]:
corpus

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [28]:
reviews = corpus.iloc[:,0]
senti = corpus.iloc[:,1]
# print(reviews)
# print(senti)

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer

# NN works on numbers so convert reviews to numbers

tfidf = TfidfVectorizer(max_features = 200)
matrix_x = tfidf.fit_transform(reviews)
# print(matrix_x.toarray())


# convert sentiments to numbers but only 0 or 1

binary_senti = [0 if i=='negative' else 1 for i in senti]
# print(binary_senti)

In [65]:
from sklearn.model_selection import train_test_split

train_reviews, test_reviews, train_senti, test_senti = train_test_split(matrix_x, binary_senti, shuffle=True, train_size = 0.8)

In [54]:
train_reviews, test_reviews
# train_senti, test_senti

(<40000x200 sparse matrix of type '<class 'numpy.float64'>'
 	with 2241929 stored elements in Compressed Sparse Row format>,
 <10000x200 sparse matrix of type '<class 'numpy.float64'>'
 	with 562626 stored elements in Compressed Sparse Row format>)

In [55]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [56]:
model = Sequential()

# 200 features with scalar values
layer1 = Dense(10, activation='sigmoid', input_shape=(200,))   # hidden layer
layer2 = Dense(1,  activation='sigmoid')    # output layer

model.add(layer1)
model.add(layer2) 

In [57]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 10)                2010      
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 11        
Total params: 2,021
Trainable params: 2,021
Non-trainable params: 0
_________________________________________________________________


In [58]:
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])

In [66]:
train_reviews = train_reviews.toarray()
test_reviews = test_reviews.toarray()

In [68]:
train_reviews = np.array(train_reviews)
train_senti = np.array(train_senti)
test_reviews = np.array(test_reviews)
test_senti = np.array(test_senti)

model.fit(train_reviews, train_senti, epochs = 3, batch_size = 64, validation_data=(test_reviews, test_senti))


Epoch 1/3
625/625 [==============================] - 1s 1ms/step - loss: 0.6935 - accuracy: 0.4965 - val_loss: 0.6932 - val_accuracy: 0.5000
Epoch 2/3
625/625 [==============================] - 1s 1ms/step - loss: 0.6930 - accuracy: 0.5103 - val_loss: 0.6925 - val_accuracy: 0.5175
Epoch 3/3
625/625 [==============================] - 1s 983us/step - loss: 0.6925 - accuracy: 0.5210 - val_loss: 0.6920 - val_accuracy: 0.5402


In [70]:
model.evaluate(test_reviews, test_senti)

313/313 [==============================] - 0s 732us/step - loss: 0.6920 - accuracy: 0.5402


[0.6920229196548462, 0.5401999950408936]

In [77]:
model.predict(test_reviews[:10])

array([[0.49482495],
       [0.4959836 ],
       [0.49000397],
       [0.49463907],
       [0.49491575],
       [0.4981155 ],
       [0.49685615],
       [0.5042055 ],
       [0.50766855],
       [0.49871626]], dtype=float32)

In [91]:
pred_senti = model.predict_classes(test_reviews[:10])
pred_senti = test_senti[:10]
print(pred_reviews, pred_senti)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]] [0 0 1 1 1 1 0 1 1 0]


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [92]:
from sklearn.metrics import precision_score, recall_score, f1_score

In [93]:
pred_senti = model.predict_classes(test_reviews)

# macro: calc scores for each label separately and then avg of all score
# micro: combine at instance level
# if equal no. of -ve and +ve labels then use macro otherwise micro
prec = precision_score(pred_senti, test_senti, average='micro')
rec = recall_score(pred_senti, test_senti, average='micro')
f1 = f1_score(pred_senti, test_senti, average='micro')

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [94]:
print(prec, rec, f1)

0.5402 0.5402 0.5402
